title: Amazon code  || Setup Amazon prime Account || Activate code  for Amazon prime
description: Create your prime account and Amazon.com/code  and enter 6-character Amazon activation code  and add channels to your list.
